name: 'thelook_ecommerce'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  thelook_ecommerce:   # Remove or update this section if not needed
    # Default materialization for all models
    +materialized: view

    # Configurations for specific models
    mart:   # Remove or update this section if not needed
      +materialized: table

    prod:   # Remove or update this section if not needed
      +materialized: view

    
   

    